var json_uktowns={
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Greenock" }, "geometry": { "type": "Point", "coordinates": [ -4.75, 55.93 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Sunderland" }, "geometry": { "type": "Point", "coordinates": [ -1.38, 54.92 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Southampton" }, "geometry": { "type": "Point", "coordinates": [ -1.4, 50.9 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Bristol" }, "geometry": { "type": "Point", "coordinates": [ -2.58, 51.45 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Bournemouth" }, "geometry": { "type": "Point", "coordinates": [ -1.9, 50.73 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Chester" }, "geometry": { "type": "Point", "coordinates": [ -2.92, 53.2 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Swansea" }, "geometry": { "type": "Point", "coordinates": [ -3.95, 51.63 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Carlisle" }, "geometry": { "type": "Point", "coordinates": [ -2.93, 54.88 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Southend-on-Sea" }, "geometry": { "type": "Point", "coordinates": [ 0.72, 51.55 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Reading" }, "geometry": { "type": "Point", "coordinates": [ -0.98, 51.47 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Leicester" }, "geometry": { "type": "Point", "coordinates": [ -1.13, 52.63 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Bradford" }, "geometry": { "type": "Point", "coordinates": [ -1.75, 53.8 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Sheffield" }, "geometry": { "type": "Point", "coordinates": [ -1.5, 53.37 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Fort William" }, "geometry": { "type": "Point", "coordinates": [ -5.11, 56.82 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Ayr" }, "geometry": { "type": "Point", "coordinates": [ -4.62, 55.45 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Aberdeen" }, "geometry": { "type": "Point", "coordinates": [ -2.08, 57.17 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Perth" }, "geometry": { "type": "Point", "coordinates": [ -3.47, 56.4 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Dundee" }, "geometry": { "type": "Point", "coordinates": [ -3.0, 56.47 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Middlesbrough" }, "geometry": { "type": "Point", "coordinates": [ -1.23, 54.58 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Coventry" }, "geometry": { "type": "Point", "coordinates": [ -1.5, 52.42 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Bath" }, "geometry": { "type": "Point", "coordinates": [ -2.35, 51.38 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Exeter" }, "geometry": { "type": "Point", "coordinates": [ -3.53, 50.7 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Cambridge" }, "geometry": { "type": "Point", "coordinates": [ 0.12, 52.2 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Kingston upon Hull" }, "geometry": { "type": "Point", "coordinates": [ -0.33, 53.75 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Penzance" }, "geometry": { "type": "Point", "coordinates": [ -5.55, 50.13 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "York" }, "geometry": { "type": "Point", "coordinates": [ -1.08, 53.97 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Blackpool" }, "geometry": { "type": "Point", "coordinates": [ -3.05, 53.83 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Dumfries" }, "geometry": { "type": "Point", "coordinates": [ -3.55, 55.07 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Scarborough" }, "geometry": { "type": "Point", "coordinates": [ -0.43, 54.28 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Plymouth" }, "geometry": { "type": "Point", "coordinates": [ -4.16, 50.39 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Ipswich" }, "geometry": { "type": "Point", "coordinates": [ 1.17, 52.07 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Norwich" }, "geometry": { "type": "Point", "coordinates": [ 1.3, 52.63 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Brighton" }, "geometry": { "type": "Point", "coordinates": [ -0.17, 50.83 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Kirkwall" }, "geometry": { "type": "Point", "coordinates": [ -2.95, 58.97 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Inverness" }, "geometry": { "type": "Point", "coordinates": [ -4.23, 57.47 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Oxford" }, "geometry": { "type": "Point", "coordinates": [ -1.25, 51.77 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Luton" }, "geometry": { "type": "Point", "coordinates": [ -0.42, 51.88 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Portsmouth" }, "geometry": { "type": "Point", "coordinates": [ -1.08, 50.8 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Peterborough" }, "geometry": { "type": "Point", "coordinates": [ -0.25, 52.58 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Nottingham" }, "geometry": { "type": "Point", "coordinates": [ -1.17, 52.97 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Stoke" }, "geometry": { "type": "Point", "coordinates": [ -2.18, 53.0 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Dover" }, "geometry": { "type": "Point", "coordinates": [ 1.3, 51.13 ] } },
{ "type": "Feature", "properties": { "featurecla": "Admin-0 region capital", "name": "Douglas" }, "geometry": { "type": "Point", "coordinates": [ -4.48, 54.15 ] } },
{ "type": "Feature", "properties": { "featurecla": "Admin-0 region capital", "name": "Edinburgh" }, "geometry": { "type": "Point", "coordinates": [ -3.22, 55.95 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Newcastle" }, "geometry": { "type": "Point", "coordinates": [ -1.6, 55.0 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Liverpool" }, "geometry": { "type": "Point", "coordinates": [ -2.92, 53.42 ] } },
{ "type": "Feature", "properties": { "featurecla": "Admin-0 region capital", "name": "Cardiff" }, "geometry": { "type": "Point", "coordinates": [ -3.23, 51.5 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Wick" }, "geometry": { "type": "Point", "coordinates": [ -3.08, 58.43 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Leeds" }, "geometry": { "type": "Point", "coordinates": [ -1.58, 53.83 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Lerwick" }, "geometry": { "type": "Point", "coordinates": [ -1.15, 60.15 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Manchester" }, "geometry": { "type": "Point", "coordinates": [ -2.25, 53.5 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Birmingham" }, "geometry": { "type": "Point", "coordinates": [ -1.92, 52.48 ] } },
{ "type": "Feature", "properties": { "featurecla": "Populated place", "name": "Glasgow" }, "geometry": { "type": "Point", "coordinates": [ -4.25, 55.88 ] } },
{ "type": "Feature", "properties": { "featurecla": "Admin-0 capital", "name": "London" }, "geometry": { "type": "Point", "coordinates": [ -0.12, 51.5 ] } }
]
}
